# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: verify_application
  pool: server
  steps:
    - task: ContrastIntegration@2
      inputs:
        ContrastService: 'TestContrastConnection'
        Application: '30b2ba47-70a0-4718-8f25-ac6641695ce9' #application ID in Contrast
        CriticalLimit: '0'
        HighLimit: '0'
        MediumLimit: '0'
        LowLimit: '0'
        NoteLimit: '0'